chore: install cerbot14

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -209,22 +209,22 @@ jobs:
         DELAY=30
         for ((i=1;i<=RETRIES;i++)); do
           echo "Attempt $i to obtain SSL certificate..."
-          ssh -i private_key -o StrictHostKeyChecking=no root@$IP << 'EOF'
-          certbot certonly --standalone -d thewise.cl -d www.thewise.cl --non-interactive --agree-tos -m ${EMAIL}
+          ssh -i private_key -o StrictHostKeyChecking=no root@$IP <<EOF
+          certbot certonly --standalone -d thewise.cl -d www.thewise.cl --non-interactive --agree-tos -m $EMAIL
           EOF
-          if [ $? -eq 0 ]; then
-            echo "SSL certificate obtained successfully."
-            break
-          else
-            echo "Failed to obtain SSL certificate. Retrying in $DELAY seconds..."
-            sleep $DELAY
+            if [ $? -eq 0 ]; then
+              echo "SSL certificate obtained successfully."
+              break
+            else
+              echo "Failed to obtain SSL certificate. Retrying in $DELAY seconds..."
+              sleep $DELAY
+            fi
+          done
+          if [ $i -eq $((RETRIES+1)) ]; then
+            echo "Failed to obtain SSL certificate after multiple attempts."
+            exit 1
           fi
-        done
-        if [ $i -eq $((RETRIES+1)) ]; then
-          echo "Failed to obtain SSL certificate after multiple attempts."
-          exit 1
-        fi
-        rm private_key
+          rm private_key
 
     - name: Validate SSL Certificate
       env:
